name: Basic Test

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Basic workflow triggered"