name: Claude

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created, edited]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-code:
    runs-on: ubuntu-latest
    if: >
      (
        (
          github.event_name == 'issues' && 
          contains(github.event.issue.body, '@claude')
        ) ||
        (
          github.event_name == 'issue_comment' && 
          contains(github.event.comment.body, '@claude')
        ) ||
        (
          github.event_name == 'pull_request' && 
          contains(github.event.pull_request.body, '@claude')
        ) ||
        (
          github.event_name == 'pull_request_review_comment' && 
          contains(github.event.comment.body, '@claude')
        ) ||
        github.event_name == 'workflow_dispatch'
      )
    steps:
      - uses: actions/checkout@v4
      - uses: anthropics/claude-code@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}