name: Claude Simple

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  claude:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Response
        uses: actions/github-script@v7
        with:
          script: |
            let issueNumber = null;
            let bodyText = '';
            
            if (context.eventName === 'issues') {
              issueNumber = context.payload.issue.number;
              bodyText = context.payload.issue.body || '';
            } else if (context.eventName === 'issue_comment') {
              issueNumber = context.payload.issue.number;
              bodyText = context.payload.comment.body || '';
            }
            
            console.log('Event:', context.eventName);
            console.log('Body:', bodyText);
            console.log('Has @claude:', bodyText.includes('@claude'));
            
            if (bodyText.includes('@claude') && issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `✅ Simple Claude workflow triggered! Event: ${context.eventName}`
              });
            }