name: Deploy to Netlify

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Build with Astro
        run: npm run build
        working-directory: ${{ env.BUILD_PATH }}
        
      - name: Deploy to Netlify (Main Branch)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Build completed successfully!"
          echo "Deploy manually to Netlify using the built files in dist/"
          echo "Or set up Netlify to deploy automatically from this repository"
          
      - name: Preview Build (PR)
        if: github.event_name == 'pull_request'
        run: |
          echo "Preview build completed successfully!"
          echo "Files are ready for preview deployment"