name: Simple Test

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Echo
        run: echo "Workflow triggered successfully"